name: Cypress Testing

on: [push]

jobs:
  Run-Cypress-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run Component Tests
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn preview
          browser: chrome
          component: true
